
28 lines (20 sloc) 442 Bytes
(function () {
    'use strict'
    //if else

    // ternarios
    // sintaxis
    //condicion ? expresion1 : expresion2;




    //switch

    debugger
    switch ("jose") {
        case 1:
            console.log("el valor es 1.");
            break;
        case "jose":
            console.log("El valor es 'jose'");
            break;
        default:
            console.log("El valor es reconocido.");
            break;
    }


})();